# Azure pipeline definition for the packaging of the solution (continuous delivery)
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr: none

variables:
# library variable groups
- group: 'build-tools'
# common task variables
- name: 'BuildConfiguration'
  value: 'Release'
- name: 'AppProjects'
  value: 'src/**/*App.csproj'
- name: 'SolutionFile'
  value: 'Devpro.BlazorSamples.sln'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use latest .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: $(dotnet.sdk.version.lts)
- task: DotNetCoreCLI@2
  displayName: 'Build .NET solution'
  inputs:
    command: 'build'
    projects: $(SolutionFile)
    arguments: '-c $(BuildConfiguration)'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    COREHOST_TRACE: 0
- task: DotNetCoreCLI@2
  displayName: 'Publish web applications'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(AppProjects)
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: false
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    COREHOST_TRACE: 0
- task: PublishBuildArtifacts@1
  displayName: 'Save artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
